package service.cloud.request.clientRequest.proxy.ose;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-05-15T10:28:16.448-05:00
 * Generated source version: 3.3.2
 */
@WebServiceClient(name = "billService",
        wsdlLocation = "https://ose.tci.net.pe/ol-ti-itcpe-2/ws/billService?wsdl",
        targetNamespace = "http://service.sunat.gob.pe")
public class BillService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.sunat.gob.pe", "billService");

    public final static QName BillServicePort = new QName("http://service.sunat.gob.pe", "BillServicePort");

    static {
        URL url = null;
        try {
            url = new URL("https://proy.ose.tci.net.pe/ol-ti-itcpe-2/ws/billService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BillService_Service.class.getName())
                    .log(java.util.logging.Level.INFO,
                            "Can not initialize the default wsdl from {0}", "https://ose.tci.net.pe/ol-ti-itcpe-2/ws/billService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BillService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BillService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BillService_Service() {
        super(WSDL_LOCATION, SERVICE);
        System.out.println();
        System.out.println(WSDL_LOCATION);
        System.out.println();
    }

    public BillService_Service(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BillService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BillService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns BillService
     */
    @WebEndpoint(name = "BillServicePort")
    public BillService getBillServicePort() {
        return super.getPort(BillServicePort, BillService.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns BillService
     */
    @WebEndpoint(name = "BillServicePort")
    public BillService getBillServicePort(WebServiceFeature... features) {
        return super.getPort(BillServicePort, BillService.class, features);
    }

}
