# configProcesador.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/VSFEBD9?createDatabaseIfNotExist=true
    username: root
    password: B1Admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update

logging:
  database:
    name: VSFEBD9
scheduled:
  fixedDelay: 10000

application:
  env: PROD
  ambiente: 'test'
  rutas:
    rutaBaseDoc: '\\192.168.1.14\b1_shf\Anexos\FESAAS'
  soap-client:
    sunat:
      base-url: 'https://e-beta.sunat.gob.pe/ol-ti-itcpfegem-beta/billService?wsdl'
    ose:
      base-url: 'https://proy.ose.tci.net.pe/ol-ti-itcpe-2/ws/billService?wsdl'

ventura:
  clientes:
    listaClientes:
      '20510910517':

        razonSocial: 'Ventura Soluciones1'

        wsUsuario: 'admin'
        wsClave: 'ventura'
        wsLocation: 'http://04082022harol.vsperufe.com/'

        emisorElecRs: '205454844881/SUNAT'
        usuarioSol: '20510910517'
        claveSol: '20510910517'

        certificadoName: "CERTIFICATE_TEST.pfx"
        certificadoPassword: '1234'
        certificadoProveedor: 'SunJSSE'
        certificadoTipoKeystore: 'Pkcs12'

        integracionWs: OSE

        mostrarSoap: 'true'
        pdfBorrador: 'true'
        impresion: 'Codigo QR'

        urlOnpremise: 'http://localhost:8101/'

        scope: 'https://api-cpe.sunat.gob.pe/'
        clientId: 'a8a6c50a-d73c-4775-9ddc-6261df69fed8'
        clientSecret: '5yr+sp24Q1J+LeYhnCooEw=='
        UserNameSunatGuias: '20510910517JVENTUR1'
        passwordSunatGuias: 'JVENTUR1'
errors:
  backend:
    gscsErrors:
      'DOC_DE_IDENTIDAD_REGISTRO_YA_EXISTE':
        systemCode: 'Y20100'
        errorCategory: 'CONFLICT'
        description: 'personId ingresado ya existe'
        razonSocial: 'Y201001'
        wsUsuario: 'admin'


server:
  port: 8083