package service.cloud.request.clientRequest.proxy.sunat.test.service;

import service.cloud.request.clientRequest.proxy.object.ObjectFactory;
import service.cloud.request.clientRequest.proxy.object.StatusResponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-04-13T12:39:48.502-05:00
 * Generated source version: 3.1.4
 */
@WebService(targetNamespace = "http://service.sunat.gob.pe", name = "billService")
@XmlSeeAlso({ObjectFactory.class})
public interface BillService {

    @WebResult(name = "ticket", targetNamespace = "")
    @RequestWrapper(localName = "sendSummary", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.SendSummary")
    @WebMethod(action = "urn:sendSummary")
    @ResponseWrapper(localName = "sendSummaryResponse2", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.SendSummaryResponse")
    String sendSummary(
            @WebParam(name = "fileName", targetNamespace = "")
            String fileName,
            @WebParam(name = "contentFile", targetNamespace = "")
            javax.activation.DataHandler contentFile
    );

    @WebResult(name = "applicationResponse", targetNamespace = "")
    @RequestWrapper(localName = "sendBill", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.SendBill")
    @WebMethod(action = "urn:sendBill")
    @ResponseWrapper(localName = "sendBillResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.SendBillResponse")
    byte[] sendBill(
            @WebParam(name = "fileName", targetNamespace = "")
            String fileName,
            @WebParam(name = "contentFile", targetNamespace = "")
            javax.activation.DataHandler contentFile
    );

    @WebResult(name = "status", targetNamespace = "")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.GetStatus")
    @WebMethod(action = "urn:getStatus")
    @ResponseWrapper(localName = "getStatusResponse2", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.GetStatusResponse")
    StatusResponse getStatus(
            @WebParam(name = "ticket", targetNamespace = "")
            String ticket
    );

    @WebResult(name = "ticket", targetNamespace = "")
    @RequestWrapper(localName = "sendPack", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.SendPack")
    @WebMethod(action = "urn:sendPack")
    @ResponseWrapper(localName = "sendPackResponse2", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.SendPackResponse")
    String sendPack(
            @WebParam(name = "fileName", targetNamespace = "")
            String fileName,
            @WebParam(name = "contentFile", targetNamespace = "")
            javax.activation.DataHandler contentFile
    );
}
