package service.cloud.request.clientRequest.proxy.sunat.production.consult;





import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.0.5
 * 2015-10-29T20:46:42.626+01:00
 * Generated source version: 3.0.5
 */
@WebServiceClient(name = "billConsultService",
        targetNamespace = "http://service.ws.consulta.comppago.electronico.registro.servicio2.sunat.gob.pe/",
        wsdlLocation = "https://www.sunat.gob.pe/ol-it-wsconscpegem/billConsultService?wsdl")
public class BillConsultService extends Service {

    public final static QName SERVICE = new QName("http://service.ws.consulta.comppago.electronico.registro.servicio2.sunat.gob.pe/", "billConsultService");

    public final static QName BillConsultServicePort = new QName("http://service.ws.consulta.comppago.electronico.registro.servicio2.sunat.gob.pe/", "BillConsultServicePort");

    /**
     * Constructor for BillConsultService class.
     *
     * @param wsdlLocation WSDL location input.
     */
    public BillConsultService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    /**
     * Constructor for BillConsultService class.
     *
     * @param wsdlLocation WSDL location input.
     * @param serviceName  Service name input.
     * @param features     Web service feature input.
     */
    public BillConsultService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * This method gets the bill service port.
     *
     * @return Returns the bill service port.
     */
    @WebEndpoint(name = "BillConsultServicePort")
    public BillService getBillConsultServicePort() {
        return super.getPort(BillConsultServicePort, BillService.class);
    }



}
