package service.cloud.request.clientRequest.proxy.sunat.production.emision;


import service.cloud.request.clientRequest.proxy.object.ObjectFactory;
import service.cloud.request.clientRequest.proxy.object.StatusResponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-04-29T09:53:51.677-05:00
 * Generated source version: 3.1.4
 */
@WebService(targetNamespace = "http://service.sunat.gob.pe", name = "billService")
@XmlSeeAlso({ObjectFactory.class})
public interface BillService {

    @WebResult(name = "ticket", targetNamespace = "")
    @RequestWrapper(localName = "sendSummary", targetNamespace = "http://service.sunat.gob.pe", className = "service.cloud.request.clientRequest.proxy.object.SendSummary")
    @WebMethod(action = "urn:sendSummary")
    @ResponseWrapper(localName = "sendSummaryResponse", targetNamespace = "http://service.sunat.gob.pe", className = "service.cloud.request.clientRequest.proxy.object.SendSummaryResponse")
    public String sendSummary(
            @WebParam(name = "fileName", targetNamespace = "")
            String fileName,
            @WebParam(name = "contentFile", targetNamespace = "")
            javax.activation.DataHandler contentFile
    );

    @WebMethod(action = "urn:sendBill")
    @RequestWrapper(localName = "sendBill", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.SendBill")
    @ResponseWrapper(localName = "sendBillResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.SendBillResponse")
    @WebResult(name = "applicationResponse", targetNamespace = "")
    public byte[] sendBill(
            @WebParam(name = "fileName", targetNamespace = "")
            String fileName,
            @WebParam(name = "contentFile", targetNamespace = "")
            javax.activation.DataHandler contentFile
    );


    @WebResult(name = "status", targetNamespace = "")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://service.sunat.gob.pe", className = "service.cloud.request.clientRequest.proxy.object.GetStatus")
    @WebMethod(action = "urn:getStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://service.sunat.gob.pe", className = "service.cloud.request.clientRequest.proxy.object.GetStatusResponse")
    public StatusResponse getStatus(
            @WebParam(name = "ticket", targetNamespace = "")
            String ticket
    );


}
