package service.cloud.request.clientRequest.proxy.sunat.production.emision;


import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2020-04-19T22:14:08.664-05:00
 * Generated source version: 3.3.2
 */
@WebServiceClient(name = "billService",
        wsdlLocation = "https://e-beta.sunat.gob.pe/ol-ti-itcpfegem-beta/billService?wsdl",
        targetNamespace = "http://service.gem.factura.comppago.registro.servicio.sunat.gob.pe/")
public class BillServiceImpl extends Service {

    public final static QName SERVICE = new QName("http://service.gem.factura.comppago.registro.servicio.sunat.gob.pe/", "billService");
    public final static QName BillServicePort = new QName("http://service.gem.factura.comppago.registro.servicio.sunat.gob.pe/", "BillServicePort");
    public BillServiceImpl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }
    /**
     * @return returns BillService
     */
    @WebEndpoint(name = "BillServicePort")
    public BillService getBillServicePort() {
        return super.getPort(BillServicePort, BillService.class);
    }
}
